version: '3'
services:
  server:
    build: .
    command: node src/server.js
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  scraper:
    build: .
    command: node src/scraper.js
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
