version: '3.8'

services:
  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  app:
    image: remazing-challenge
    build: .
    command: node dist/app.js
    depends_on:
      - mongo
    restart: unless-stopped

  server:
    image: remazing-challenge
    build: .
    command: node dist/server.js
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
